// <auto-generated />
using System;
using CUDJobAPiIdentity.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CudJobApiIdentity.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210928130052_Addingsectorandprogram")]
    partial class Addingsectorandprogram
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("CUDJobAPiIdentity.Models.Companies", b =>
                {
                    b.Property<int>("CompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Certificatepath")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("CompanyStrength")
                        .HasColumnType("Nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HealthMeasures")
                        .HasColumnType("Nvarchar(200)");

                    b.Property<DateTime>("LicenseExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NotesID")
                        .HasColumnType("int");

                    b.Property<int>("SectorID")
                        .HasColumnType("int");

                    b.Property<int?>("StatusIDs")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmailID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Website")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("profileImgpath")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CompanyID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("NotesID");

                    b.HasIndex("SectorID");

                    b.HasIndex("StatusIDs");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("CUDJobAPiIdentity.Models.JobCategory", b =>
                {
                    b.Property<int>("JobCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobCategoryName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("JobCategoryId");

                    b.ToTable("JobCategory");
                });

            modelBuilder.Entity("CUDJobAPiIdentity.Models.Jobs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Applytype")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpectedSalary")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Experience")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExperienceID")
                        .HasColumnType("int");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("JobCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("JobTypeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastApplyDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NotesID")
                        .HasColumnType("int");

                    b.Property<string>("Qualification")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReguiredSkills")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shortheading")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("StatusIDs")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("durationID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyID");

                    b.HasIndex("ExperienceID");

                    b.HasIndex("JobCategoryId");

                    b.HasIndex("JobTypeID");

                    b.HasIndex("NotesID");

                    b.HasIndex("StatusIDs");

                    b.HasIndex("durationID");

                    b.ToTable("JobModel");
                });

            modelBuilder.Entity("CUDJobAPiIdentity.Models.StudentEducation", b =>
                {
                    b.Property<int>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CertificateDiploma")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Certificate_Diploma");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Completion_Date");

                    b.Property<byte?>("CompletionPercent")
                        .HasColumnType("tinyint")
                        .HasColumnName("Completion_Percent");

                    b.Property<DateTime>("CreateddDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("CurrrentSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Degree")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("Institution")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("Major")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Start_Date");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("EducationId");

                    b.HasIndex("StudentID");

                    b.ToTable("Studenteducation");
                });

            modelBuilder.Entity("CUDJobAPiIdentity.Models.StudentExperience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(100)
                        .HasColumnType("Nvarchar(100)")
                        .HasColumnName("Company_Name");

                    b.Property<string>("Companywebsite")
                        .HasMaxLength(200)
                        .HasColumnType("Nvarchar(200)")
                        .HasColumnName("Company_website");

                    b.Property<int>("CountryCode")
                        .HasColumnType("int")
                        .HasColumnName("Country_Code");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("Nvarchar(100)")
                        .HasColumnName("Department");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("End_Date");

                    b.Property<string>("JobDescription")
                        .HasMaxLength(5000)
                        .HasColumnType("Nvarchar(5000)")
                        .HasColumnName("Job_Description");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(100)
                        .HasColumnType("Nvarchar(100)")
                        .HasColumnName("Job_Title");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("Nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Start_Month");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryID");

                    b.HasIndex("StudentID");

                    b.ToTable("StudentExperience");
                });

            modelBuilder.Entity("CUDJobAPiIdentity.Models.StudentSeekers", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Credihours")
                        .HasMaxLength(10)
                        .HasColumnType("Nvarchar(10)");

                    b.Property<string>("CudStudentID")
                        .HasMaxLength(50)
                        .HasColumnType("Nvarchar(50)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailID")
                        .HasMaxLength(50)
                        .HasColumnType("Nvarchar(50)");

                    b.Property<string>("EmailID2")
                        .HasMaxLength(50)
                        .HasColumnType("Nvarchar(50)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("Nvarchar(10)");

                    b.Property<string>("Intern")
                        .HasMaxLength(5)
                        .HasColumnType("Nvarchar(5)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("MaritalStatus")
                        .HasMaxLength(50)
                        .HasColumnType("Nvarchar(50)");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(30)
                        .HasColumnType("Nvarchar(30)");

                    b.Property<string>("MobileNumber2")
                        .HasMaxLength(30)
                        .HasColumnType("Nvarchar(30)");

                    b.Property<string>("Objective")
                        .HasMaxLength(300)
                        .HasColumnType("Nvarchar(300)");

                    b.Property<string>("Password")
                        .HasColumnType("Nvarchar(50)");

                    b.Property<string>("Porgram")
                        .HasMaxLength(50)
                        .HasColumnType("Nvarchar(50)");

                    b.Property<int>("ProgramID")
                        .HasColumnType("int");

                    b.Property<string>("Resumepath")
                        .HasMaxLength(150)
                        .HasColumnType("Nvarchar(150)");

                    b.Property<string>("Skillset")
                        .HasMaxLength(1000)
                        .HasColumnType("Nvarchar(1000)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisaStatus")
                        .HasMaxLength(50)
                        .HasColumnType("Nvarchar(50)");

                    b.Property<string>("profileImgpath")
                        .HasMaxLength(150)
                        .HasColumnType("Nvarchar(150)");

                    b.HasKey("StudentID");

                    b.HasIndex("ProgramID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.Address", b =>
                {
                    b.Property<int>("AddressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address1")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<int>("AddressTypeID")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("Nvarchar(50)");

                    b.Property<int>("CountryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateddDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Nationality")
                        .HasColumnType("int");

                    b.Property<int>("PinCode")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasColumnType("Nvarchar(50)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("AddressID");

                    b.HasIndex("CountryID");

                    b.HasIndex("Nationality");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.AppliedJobs", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("AppliedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("StatusID")
                        .HasColumnType("int");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<int>("jobID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("StatusID");

                    b.HasIndex("StudentID");

                    b.HasIndex("jobID");

                    b.ToTable("AppliedJobs");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.Awards", b =>
                {
                    b.Property<int>("AwardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("AwardDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AwardName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("AwardID");

                    b.HasIndex("StudentID");

                    b.ToTable("Awards");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.CompanyAddressCollection", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AddressID")
                        .HasColumnType("int");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AddressID");

                    b.HasIndex("CompanyID");

                    b.ToTable("CompanyAddressCollection");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.CompanyCategory", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryID");

                    b.ToTable("CompanyCategory");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.CompanyContacts", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<string>("Contact_No")
                        .HasColumnType("Nvarchar(50)");

                    b.Property<DateTime>("CreateddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailID")
                        .HasColumnType("Nvarchar(50)");

                    b.Property<string>("FirstName")
                        .HasColumnType("Nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasColumnType("Nvarchar(50)");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.ToTable("CompanyContacts");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.CompanyOptional", b =>
                {
                    b.Property<int>("OptionalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CUD_Incubator_Project")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<string>("Do_you_cover_incaseof_work_accidents")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FlexibleHours_forFulltime")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FlexibleHours_forInternship")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FlexibleHours_forParttime")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Fulltimeoffer")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Internshipoffer")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Morethan_Onemonth_Internship")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Onemonth_Internship")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PaidInternship")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Partcipate_CUDAnnualcareerfair")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Partcipateorsponsor_CUDEvents")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Parttimeoffer")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Share_ContactDetails")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Workingfromoffice_forFulltime")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Workingfromoffice_forInternship")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Workingfromoffice_forParttime")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Workshops_tostudent")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("OptionalID");

                    b.HasIndex("CompanyID")
                        .IsUnique();

                    b.ToTable("CompanyOptional");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.CompanyPortfolio", b =>
                {
                    b.Property<int>("PortfolioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<string>("portfolio")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("PortfolioID");

                    b.HasIndex("CompanyID");

                    b.ToTable("CompanyPortfolio");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.CompanySectors", b =>
                {
                    b.Property<int>("SectorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SectorID");

                    b.ToTable("CompanySectors");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.CountryCode", b =>
                {
                    b.Property<int>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CountryID");

                    b.ToTable("CountryCode");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.DaysPerWeekOptions", b =>
                {
                    b.Property<int>("DaysPerWeekID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Options")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DaysPerWeekID");

                    b.ToTable("DaysPerWeekOptions");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.HoursPerWeekOptions", b =>
                {
                    b.Property<int>("HoursPerWeekID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Options")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HoursPerWeekID");

                    b.ToTable("HoursPerWeekOptions");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.JobExperiences", b =>
                {
                    b.Property<int>("ExperienceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ExperienceType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ExperienceID");

                    b.ToTable("JobExperiences");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.JobOptions", b =>
                {
                    b.Property<int>("JoboptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("FlexibleHours")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("ID")
                        .HasColumnType("int");

                    b.Property<string>("Paid")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Workfromoffice")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("JoboptionID");

                    b.HasIndex("ID")
                        .IsUnique()
                        .HasFilter("[ID] IS NOT NULL");

                    b.ToTable("JobOptions");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.JobStatuses", b =>
                {
                    b.Property<int>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Status")
                        .HasColumnType("Nvarchar(50)");

                    b.HasKey("StatusID");

                    b.ToTable("JobStatuses");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.Job_durations", b =>
                {
                    b.Property<int>("durationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("durationID");

                    b.ToTable("Job_durations");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.JobsWorkAvailability", b =>
                {
                    b.Property<int>("AvailabilityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("DaysPerWeekID")
                        .HasColumnType("int");

                    b.Property<int>("HoursPerWeekID")
                        .HasColumnType("int");

                    b.Property<int>("JobID")
                        .HasColumnType("int");

                    b.HasKey("AvailabilityID");

                    b.HasIndex("DaysPerWeekID");

                    b.HasIndex("HoursPerWeekID");

                    b.HasIndex("JobID");

                    b.ToTable("JobsWorkAvailability");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.Jobtypes", b =>
                {
                    b.Property<int>("JobTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("Varchar(50)");

                    b.HasKey("JobTypeID");

                    b.ToTable("Jobtypes");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.Languages", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Language")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<string>("level")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID");

                    b.HasIndex("StudentID");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.Memberships", b =>
                {
                    b.Property<int>("MembershipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Organisation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("MembershipID");

                    b.HasIndex("StudentID");

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.Projects", b =>
                {
                    b.Property<int>("PorjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Attachment")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Enddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Links")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Organisation")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Outcome")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Role")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("Startdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<string>("Tittle")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("PorjectID");

                    b.HasIndex("StudentID");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.Statuses", b =>
                {
                    b.Property<int?>("StatusIDs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("MyProperty")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StatusIDs");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.StatusesNotes", b =>
                {
                    b.Property<int?>("NotesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("StatusID")
                        .HasColumnType("int");

                    b.HasKey("NotesID");

                    b.ToTable("StatusesNotes");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.StudentAddressCollection", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AddressID")
                        .HasColumnType("int");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AddressID");

                    b.HasIndex("StudentID");

                    b.ToTable("StudentAddressCollection");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.StudentWorkAvailability", b =>
                {
                    b.Property<int>("AvailabilityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("DaysPerWeekID")
                        .HasColumnType("int");

                    b.Property<int>("HoursPerWeekID")
                        .HasColumnType("int");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("AvailabilityID");

                    b.HasIndex("DaysPerWeekID");

                    b.HasIndex("HoursPerWeekID");

                    b.HasIndex("StudentID");

                    b.ToTable("StudentWorkAvailability");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.Studentportfolio", b =>
                {
                    b.Property<int>("PortfolioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<string>("portfolio")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("PortfolioID");

                    b.HasIndex("StudentID");

                    b.ToTable("Studentportfolio");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.programs", b =>
                {
                    b.Property<int>("ProgramID")
                        .HasColumnType("int");

                    b.Property<string>("ProgramName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProgramID");

                    b.ToTable("programs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("CUDJobAPiIdentity.Models.Companies", b =>
                {
                    b.HasOne("CUDJobApiIdentity.Models.CompanyCategory", "companycategory")
                        .WithMany("Companies")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CUDJobApiIdentity.Models.StatusesNotes", "StatusesNotes")
                        .WithMany("Companies")
                        .HasForeignKey("NotesID");

                    b.HasOne("CUDJobApiIdentity.Models.CompanySectors", "CompanySectors")
                        .WithMany("Companies")
                        .HasForeignKey("SectorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CUDJobApiIdentity.Models.Statuses", "Statuses")
                        .WithMany("Companies")
                        .HasForeignKey("StatusIDs");

                    b.Navigation("companycategory");

                    b.Navigation("CompanySectors");

                    b.Navigation("Statuses");

                    b.Navigation("StatusesNotes");
                });

            modelBuilder.Entity("CUDJobAPiIdentity.Models.Jobs", b =>
                {
                    b.HasOne("CUDJobAPiIdentity.Models.Companies", "Companies")
                        .WithMany("Jobs")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CUDJobApiIdentity.Models.JobExperiences", "Experiences")
                        .WithMany("Jobs")
                        .HasForeignKey("ExperienceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CUDJobAPiIdentity.Models.JobCategory", "jobcategories")
                        .WithMany("Jobs")
                        .HasForeignKey("JobCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CUDJobApiIdentity.Models.Jobtypes", "Jobtypes")
                        .WithMany("Jobs")
                        .HasForeignKey("JobTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CUDJobApiIdentity.Models.StatusesNotes", "StatusesNotes")
                        .WithMany("Jobs")
                        .HasForeignKey("NotesID");

                    b.HasOne("CUDJobApiIdentity.Models.Statuses", "Statuses")
                        .WithMany("Jobs")
                        .HasForeignKey("StatusIDs");

                    b.HasOne("CUDJobApiIdentity.Models.Job_durations", "Job_durations")
                        .WithMany("Jobs")
                        .HasForeignKey("durationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Companies");

                    b.Navigation("Experiences");

                    b.Navigation("Job_durations");

                    b.Navigation("jobcategories");

                    b.Navigation("Jobtypes");

                    b.Navigation("Statuses");

                    b.Navigation("StatusesNotes");
                });

            modelBuilder.Entity("CUDJobAPiIdentity.Models.StudentEducation", b =>
                {
                    b.HasOne("CUDJobAPiIdentity.Models.StudentSeekers", "StudentSeeker")
                        .WithMany("StudentEducations")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentSeeker");
                });

            modelBuilder.Entity("CUDJobAPiIdentity.Models.StudentExperience", b =>
                {
                    b.HasOne("CUDJobApiIdentity.Models.CompanyCategory", "companycategory")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CUDJobAPiIdentity.Models.StudentSeekers", "StudentSeeker")
                        .WithMany("StudentExperiences")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("companycategory");

                    b.Navigation("StudentSeeker");
                });

            modelBuilder.Entity("CUDJobAPiIdentity.Models.StudentSeekers", b =>
                {
                    b.HasOne("CUDJobApiIdentity.Models.programs", "programs")
                        .WithMany("Students")
                        .HasForeignKey("ProgramID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("programs");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.Address", b =>
                {
                    b.HasOne("CUDJobApiIdentity.Models.CountryCode", "CountryCode")
                        .WithMany("address")
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CUDJobApiIdentity.Models.CountryCode", "NationalityCode")
                        .WithMany("Nationalityaddress")
                        .HasForeignKey("Nationality");

                    b.Navigation("CountryCode");

                    b.Navigation("NationalityCode");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.AppliedJobs", b =>
                {
                    b.HasOne("CUDJobApiIdentity.Models.JobStatuses", "JobStatuses")
                        .WithMany("AppliedJobs")
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CUDJobAPiIdentity.Models.StudentSeekers", "Student")
                        .WithMany("AppliedJobs")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CUDJobAPiIdentity.Models.Jobs", "job")
                        .WithMany("AppliedJobs")
                        .HasForeignKey("jobID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("job");

                    b.Navigation("JobStatuses");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.Awards", b =>
                {
                    b.HasOne("CUDJobAPiIdentity.Models.StudentSeekers", "StudentSeeker")
                        .WithMany("Award")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentSeeker");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.CompanyAddressCollection", b =>
                {
                    b.HasOne("CUDJobApiIdentity.Models.Address", "Address")
                        .WithMany("CompanyAddresses")
                        .HasForeignKey("AddressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CUDJobAPiIdentity.Models.Companies", "Companies")
                        .WithMany("addresses")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Companies");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.CompanyContacts", b =>
                {
                    b.HasOne("CUDJobAPiIdentity.Models.Companies", "Companies")
                        .WithMany("CompanyContacts")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Companies");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.CompanyOptional", b =>
                {
                    b.HasOne("CUDJobAPiIdentity.Models.Companies", "Companies")
                        .WithOne("CompanyOptional")
                        .HasForeignKey("CUDJobApiIdentity.Models.CompanyOptional", "CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Companies");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.CompanyPortfolio", b =>
                {
                    b.HasOne("CUDJobAPiIdentity.Models.Companies", "Companies")
                        .WithMany("CompanyPortfolio")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Companies");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.JobOptions", b =>
                {
                    b.HasOne("CUDJobAPiIdentity.Models.Jobs", "Jobs")
                        .WithOne("JobOptions")
                        .HasForeignKey("CUDJobApiIdentity.Models.JobOptions", "ID");

                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.JobsWorkAvailability", b =>
                {
                    b.HasOne("CUDJobApiIdentity.Models.DaysPerWeekOptions", "DaysPerWeek")
                        .WithMany()
                        .HasForeignKey("DaysPerWeekID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CUDJobApiIdentity.Models.HoursPerWeekOptions", "HoursPerWeek")
                        .WithMany()
                        .HasForeignKey("HoursPerWeekID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CUDJobAPiIdentity.Models.Jobs", "Jobs")
                        .WithMany("JobsWorkAvailability")
                        .HasForeignKey("JobID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DaysPerWeek");

                    b.Navigation("HoursPerWeek");

                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.Languages", b =>
                {
                    b.HasOne("CUDJobAPiIdentity.Models.StudentSeekers", "StudentSeeker")
                        .WithMany("Languages")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentSeeker");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.Memberships", b =>
                {
                    b.HasOne("CUDJobAPiIdentity.Models.StudentSeekers", "StudentSeeker")
                        .WithMany("Memberships")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentSeeker");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.Projects", b =>
                {
                    b.HasOne("CUDJobAPiIdentity.Models.StudentSeekers", "StudentSeeker")
                        .WithMany("Projects")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentSeeker");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.StudentAddressCollection", b =>
                {
                    b.HasOne("CUDJobApiIdentity.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CUDJobAPiIdentity.Models.StudentSeekers", "Student")
                        .WithMany("StudentAddresses")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.StudentWorkAvailability", b =>
                {
                    b.HasOne("CUDJobApiIdentity.Models.DaysPerWeekOptions", "DaysPerWeekOptions")
                        .WithMany()
                        .HasForeignKey("DaysPerWeekID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CUDJobApiIdentity.Models.HoursPerWeekOptions", "HoursPerWeekOptions")
                        .WithMany()
                        .HasForeignKey("HoursPerWeekID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CUDJobAPiIdentity.Models.StudentSeekers", "StudentSeeker")
                        .WithMany("StudentWorkAvailability")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DaysPerWeekOptions");

                    b.Navigation("HoursPerWeekOptions");

                    b.Navigation("StudentSeeker");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.Studentportfolio", b =>
                {
                    b.HasOne("CUDJobAPiIdentity.Models.StudentSeekers", "StudentSeeker")
                        .WithMany("Studentportfolio")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentSeeker");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CUDJobAPiIdentity.Models.Companies", b =>
                {
                    b.Navigation("addresses");

                    b.Navigation("CompanyContacts");

                    b.Navigation("CompanyOptional");

                    b.Navigation("CompanyPortfolio");

                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("CUDJobAPiIdentity.Models.JobCategory", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("CUDJobAPiIdentity.Models.Jobs", b =>
                {
                    b.Navigation("AppliedJobs");

                    b.Navigation("JobOptions");

                    b.Navigation("JobsWorkAvailability");
                });

            modelBuilder.Entity("CUDJobAPiIdentity.Models.StudentSeekers", b =>
                {
                    b.Navigation("AppliedJobs");

                    b.Navigation("Award");

                    b.Navigation("Languages");

                    b.Navigation("Memberships");

                    b.Navigation("Projects");

                    b.Navigation("StudentAddresses");

                    b.Navigation("StudentEducations");

                    b.Navigation("StudentExperiences");

                    b.Navigation("Studentportfolio");

                    b.Navigation("StudentWorkAvailability");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.Address", b =>
                {
                    b.Navigation("CompanyAddresses");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.CompanyCategory", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.CompanySectors", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.CountryCode", b =>
                {
                    b.Navigation("address");

                    b.Navigation("Nationalityaddress");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.JobExperiences", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.JobStatuses", b =>
                {
                    b.Navigation("AppliedJobs");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.Job_durations", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.Jobtypes", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.Statuses", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.StatusesNotes", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("CUDJobApiIdentity.Models.programs", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
